### ISSUE TITLE
IDW slow in the wizard

### ISSUE THREAD

**Issue by jtpesone** [GispoCoding/eis_qgis_plugin#143]
BUG DESCRIPTION
IDW interpolation in the Wizard's proxy processing does not work (keeps on processing for more than half an hour, no result). IDW in the EIS Processing Algorithms works fine. Kriging option works fast also through the Wizard.

REPRO STEPS
1. In the wizard Mineral system proxies page, select IOCG Mineral system and Study scale "Regional"
![image](https://github.com/GispoCoding/eis_qgis_plugin/assets/4497957/c23677ce-0362-4574-aefe-64cfdd9ada94)

2. Press the Process button for Distance to high Fe concentrations

4. Input data can be obtained from johanna.pesonen@gtk.fi. Also available via project's Nextcloud. Input vector layer is in the folder "Geochemical data/Vector files", and the Base raster in the folder "Geophysical data/AEM"
![image](https://github.com/GispoCoding/eis_qgis_plugin/assets/4497957/827c2447-a489-4a1d-bd7e-93ec7ea15593)

Expected behavior
IDW would run in appr.  2 minutes.

**Desktop (please complete the following information):**
 - Plugin: 0.2
 - QGIS 3.28.6
 - Python: 3.10
 - OS: Windows 10

**Comment by nmaarnio** [comment]
This is not slowness of the algorith, but some kind of bug that prevents the execution to finish. Again, it would be better to investigate these kind of bugs using the processing algorithm directly, since it will show the progress bar and execution time (if it finishes).

This issue might get resolved when PR #146 is merged. At least I could run IDW without any issues in Wizard.

**Comment by nmaarnio** [comment]
The stuck execution bug has been fixed, closing.
